### ISSUE TITLE
No module named 'local_lib'

### ISSUE THREAD

**Issue by wolf2127** [Amir-Samadi/SAFE-RL#1]
Hello, when I try to reproduce your work, I show the following problem after configuring the environment, do you know how to solve this problem?
![选区_001](https://github.com/Amir-Samadi/SAFE-RL/assets/116620093/125b9698-1171-4f4f-8b33-9f94978290eb)

**Comment by Amir-Samadi** [comment]
Hi there!
Sorry for the confusion. It seems that it comes from a previous version. There is no need for that import anymore. I have updated the code, and you can also remove that line. Let me know if you encounter any other issues.

**Comment by wolf2127** [comment]
Hi, when I try to comment out no module named local_lib, I get this problem : no module named core
![选区_002](https://github.com/Amir-Samadi/SAFE-RL/assets/116620093/1afe8b82-8f63-4f23-bba7-b880ae63dc4f)

**Comment by Amir-Samadi** [comment]
I have updated the code and the requirements.txt file, and I have also added the 'core' folder. Please replace all the files and try again. Let me know if you still encounter any errors.

**Comment by wolf2127** [comment]
ok, l will have a try. Thank you.
